replicaCount: 1
image:
  repository: producer
  tag: "14"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  nodePort: 30010
serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 15s
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 50
