apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'kafka_consumergroup_lag{job!="prometheus"}'
        seriesFilters: []
        resources:
          overrides: {}
        name:
          matches: "^(.*)$"
          as: "kafka_consumergroup_lag"
        metricsQuery: 'max(kafka_consumergroup_lag{<<.LabelMatchers>>})'
