kafka:
  kraft:
    enabled: true
  controller:
    replicaCount: 1
  broker:
    replicaCount: 1
  service:
    type: ClusterIP
  persistence:
    enabled: false
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
# kafka-exporter is enabled via monitoring chart (see monitoring overlay)
