apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: producer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      name: http
