apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'REPLACE_ME_GITOPS_REPO'
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
