apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/infra-gitops.git
    targetRevision: main
    path: charts/consumer
    helm:
      valueFiles:
        - overlays/dev/consumer-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: consumer-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
