apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/infra-gitops.git
    targetRevision: main
    path: charts/producer
    helm:
      valueFiles:
        - overlays/prod/producer-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: producer-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
