apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: consumer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      name: http
