replicaCount: 1
image:
  repository: REPLACE_ME_REGISTRY/consumer
  tag: latest
service:
  type: ClusterIP
  port: 80
containerPort: 3001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  path: /healthz
  port: 3001

readinessProbe:
  path: /healthz
  port: 3001

# HPA config: default not using Kafka-lag external metric (you will enable via overlay)
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpuUtilizationPercent: 60
  kafkaLag:
    enabled: false
    metricName: kafka_consumergroup_lag
    threshold: 100

prometheus:
  servicemonitor:
    enabled: true
    interval: 15s
    path: /metrics
    port: http
